abstract final class RouteNames {
  static const splash = '/';
  static const onboarding = '/onboarding';
  static const auth = '/auth';
  static const roleSelector = '/role-selector';
  static const home = '/home';
  static const search = '/search';
  static const listingDetails = '/listing';
  static const bookingRequest = '/booking-request';
  static const bookingPayment = '/booking-payment';
  static const reviewSubmit = '/review-submit';
  static const favorites = '/favorites';
  static const bookings = '/bookings';
  static const hostRequests = '/host-requests';
  static const chatList = '/chat';
  static const premiumPaywall = '/premium';
  static const support = '/support';
  static const settings = '/settings';
}
