# Generated by Django 5.2.12 on 2026-03-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='listing',
            name='district',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='listing',
            name='free_stay_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='listing',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='listing',
            name='max_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='listing',
            name='metro',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='listing',
            name='min_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='show_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(
                choices=[('home', 'Home'), ('room', 'Room'), ('free_stay', 'Free Stay')],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
